M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 17 15:40:36 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-17T15:40:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X65.976Y-44.1
X65.976Y-49.88
X65.976Y-58.959
X65.976Y-64.739
T0
M30
